# Generated by Django 6.0.3 on 2026-04-07 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='email_reminder_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='email_reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
