# Generated by Django 6.0.4 on 2026-04-20 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_appointment_email_reminder_sent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='soap_reminder_last_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
