# Generated by Django 6.0.4 on 2026-04-20 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_appointment_completed_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='soap_reminder_last_sent_at',
            new_name='soap_note_reminder_last_sent_at',
        ),
    ]
