# Generated by Django 6.0.3 on 2026-03-15 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practitioners', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PractitionerService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('practitioner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services_offered', to='practitioners.practitioner')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practitioners', to='services.service')),
            ],
            options={
                'unique_together': {('practitioner', 'service')},
            },
        ),
    ]
